import {writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve, dirname} from 'node:path';
import {createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {pages} from './content.mjs';
import {esc, arrow, btn} from './ui.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const site = 'https://cdm-lifesupport.com';
const assetVersion = createHash('sha256').update(await readFile(resolve(root,'assets/site.css'))).update(await readFile(resolve(root,'assets/site.js'))).digest('hex').slice(0,10);
const groups = [
  ['about','CDMについて','about.html', [['about.html','CDMについて'],['philosophy.html','理念・行動指針'],['message.html','代表メッセージ'],['strength.html','私たちの強み']]],
  ['business','事業内容','business.html', [['business.html','事業一覧'],['sales.html','営業代行'],['promotion.html','販促支援'],['systems.html','システム販売'],['quality.html','品質管理'],['flow.html','支援の流れ'],['faq.html','よくあるご質問']]],
  ['cases','支援事例','cases.html', [['cases.html','支援事例一覧'],['case-promotion.html','販促支援の取り組み'],['case-sales.html','新規顧客開拓の取り組み'],['case-crm.html','CRMの活用イメージ']]],
  ['company','会社情報','company.html', [['company.html','会社概要'],['history.html','沿革'],['numbers.html','数字で見るCDM'],['partner.html','パートナー募集']]],
  ['news','お知らせ','news.html', [['news.html','お知らせ一覧']]],
  ['recruit','採用情報','recruit.html', [['recruit.html','採用情報'],['careers.html','働く環境・キャリア'],['jobs.html','募集要項']]]
];
const header = p => `<a class="skip-link" href="#main">本文へ移動</a><header class="site-header"><div class="wrap nav"><a class="brand" href="index.html" aria-label="合同会社CDM トップへ"><img src="assets/cdm-logo.png" width="48" height="48" alt=""><span>合同会社CDM</span></a><button class="menu-toggle" type="button" aria-controls="site-nav" aria-expanded="false"><span>メニュー</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 7h18M3 12h18M3 17h18" fill="none" stroke="currentColor" stroke-width="1.5"/></svg></button><nav id="site-nav" class="main-nav" aria-label="メインナビゲーション">${groups.map(([g,name,url]) => `<a href="${url}"${p.group===g ? ' class="active"' : ''}${p.file===url ? ' aria-current="page"' : ''}>${name}</a>`).join('')}<a class="nav-cta" href="contact.html"${p.file==='contact.html'?' aria-current="page"':''}>お問い合わせ</a></nav></div></header>`;
const footer = () => `<footer class="site-footer"><div class="wrap"><div class="footer-top"><a class="brand" href="index.html"><img src="assets/cdm-logo.png" width="48" height="48" loading="lazy" alt=""><span>合同会社CDM</span></a><p>現場から、事業を前へ。</p></div><div class="footer-links">${groups.map(([,name,,links]) => `<div><h2>${name}</h2>${links.map(([url,label])=>`<a href="${url}">${label}</a>`).join('')}</div>`).join('')}</div><div class="footer-bottom"><small>© 2026 CDM LLC.</small><div><a href="contact.html">お問い合わせ</a><a href="privacy.html">プライバシーポリシー</a><a href="site-policy.html">サイトポリシー</a></div></div></div></footer>`;
const cta = () => `<section class="contact-band"><div class="wrap"><div><h2>次の一歩を、<br class="mobile-break">一緒につくる。</h2><p>営業・販促・システムの相談から、採用・パートナー連携まで。</p></div>${btn('contact.html','お問い合わせ')}</div></section>`;
const demo = () => `<dialog id="crm-demo" aria-labelledby="demo-title"><div class="demo-head"><h2 id="demo-title">CRMの画面イメージ</h2><button type="button" data-close-demo aria-label="画面イメージを閉じる"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5l14 14M19 5L5 19" fill="none" stroke="currentColor" stroke-width="1.5"/></svg></button></div><div class="demo-body"><p>画面はイメージです。画像内の企業名・金額などはデモ表示です。実際の提供機能・画面は、ご提案内容によって異なります。</p><figure><figcaption>01　ダッシュボード｜顧客・案件・入金・タスクの状況</figcaption><img src="assets/crm-demo-dashboard.png" width="1487" height="1058" loading="lazy" alt="CRMのダッシュボードの画面イメージ。進行案件数、入金予定、要対応案件とタスクを一覧表示。"></figure><figure><figcaption>02　商材・ステータス設定｜業務に合わせた進行フロー</figcaption><img src="assets/crm-demo-settings.png" width="1487" height="1058" loading="lazy" alt="CRMの商材・ステータス設定画面のイメージ。商材ごとの入金単価と案件ステータスを設定。"></figure><p class="demo-direct">画像を大きく表示：<a href="assets/crm-demo-dashboard.png" target="_blank" rel="noopener">ダッシュボード</a> / <a href="assets/crm-demo-settings.png" target="_blank" rel="noopener">商材・ステータス設定</a></p></div></dialog>`;

for (const [file, p] of Object.entries(pages)) {
  p.file=file;
  const canonical = `${site}/${file==='index.html'?'':file}`;
  const title = file==='index.html' ? '合同会社CDM｜営業代行・販促支援・システム販売' : `${p.title}｜合同会社CDM`;
  const group = groups.find(([g]) => g===p.group);
  const breadcrumbs = file==='index.html' ? [] : [{name:'TOP',url:`${site}/`},...(group && group[2]!==file ? [{name:group[1],url:`${site}/${group[2]}`}] : []),{name:p.title,url:canonical}];
  const schema = [{'@context':'https://schema.org','@type':'Organization',name:'合同会社CDM',url:site,logo:`${site}/assets/cdm-logo.png`,email:'ceo@cdm-lifesupport.com',telephone:'070-9129-0907',foundingDate:'2025-02',address:{'@type':'PostalAddress',addressRegion:'神奈川県',addressLocality:'平塚市',streetAddress:'東八幡2-9-29',addressCountry:'JP'}},...(breadcrumbs.length ? [{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:breadcrumbs.map((b,i)=>({'@type':'ListItem',position:i+1,name:b.name,item:b.url}))}] : []),...(p.schema||[])];
  const hero = file==='index.html' ? '' : `<div class="wrap"><nav class="breadcrumbs" aria-label="パンくずリスト"><ol>${breadcrumbs.map((b,i)=>`<li>${i===breadcrumbs.length-1 ? `<span aria-current="page">${esc(b.name)}</span>` : `<a href="${b.url}">${esc(b.name)}</a>`}</li>`).join('')}</ol></nav><div class="page-hero"><h1>${p.heading||esc(p.title)}</h1><p>${p.lead}</p></div>${group ? `<nav class="section-nav" aria-label="${group[1]}のページ">${group[3].map(([url,name])=>`<a href="${url}"${url===file?' aria-current="page"':''}>${name}</a>`).join('')}</nav>` : ''}</div>`;
  const document = `<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(p.description||p.lead.replace(/<[^>]*>/g,''))}"><meta name="robots" content="${file==='404.html'?'noindex,follow':'index,follow'}"><link rel="canonical" href="${canonical}"><link rel="icon" type="image/png" sizes="500x500" href="/favicon.png?v=cdm"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="manifest" href="/site.webmanifest"><meta property="og:type" content="${p.article?'article':'website'}"><meta property="og:site_name" content="合同会社CDM"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(p.description||p.lead.replace(/<[^>]*>/g,''))}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${site}/assets/cdm-logo.png"><meta name="twitter:card" content="summary"><meta name="theme-color" content="#091a33"><link rel="stylesheet" href="assets/site.css?v=${assetVersion}"><script src="assets/site.js?v=${assetVersion}" defer></script><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body>${header(p)}<main id="main" tabindex="-1">${hero}${p.body}</main>${p.noCta?'':cta()}${footer()}${p.demo?demo():''}</body></html>\n`;
  const formatted = document.replace(/(<\/(?:head|header|main|section|article|div|footer|nav|form|aside|details|h[1-6]|figure|fieldset)>)/g, '$1\n').replace(/(<(?:head|header|main|section|article|div|footer|nav|form|aside|details|h[1-6]|figure|fieldset)\b)/g, '\n$1');
  await writeFile(resolve(root,file),formatted);
}
await writeFile(resolve(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${Object.keys(pages).filter(f=>f!=='404.html').map(f=>`<url><loc>${site}/${f==='index.html'?'':f}</loc></url>`).join('')}</urlset>\n`);
console.log(`Built ${Object.keys(pages).length} static pages (${assetVersion}).`);
